# Generated by Django 4.1.1 on 2022-10-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoias',
            new_name='categorias',
        ),
    ]
